#!/usr/bin/env python3
"""Render STATUS.md from reports/security_scorecard.json."""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCORECARD_PATH = REPO_ROOT / "reports" / "security_scorecard.json"
STATUS_PATH = REPO_ROOT / "STATUS.md"


def main() -> int:
    if not SCORECARD_PATH.exists():
        raise FileNotFoundError(f"missing scorecard: {SCORECARD_PATH}")

    payload = json.loads(SCORECARD_PATH.read_text(encoding="utf-8"))

    attack = payload["attack_corpus"]
    benign = payload["benign_corpus"]
    redteam = payload["redteam_gate"]

    content = f"""# MVAR Security Status

**Last updated:** {payload['generated_at']}  
**Version:** {payload['version']}  
**Commit:** {payload['commit']}

## Attack Corpus Coverage

| Metric | Value |
|---|---|
| Total vectors | {attack['total_vectors']} |
| Blocked | {attack['blocked']} |
| Block rate | {attack['block_rate']:.1%} |

## Benign Corpus

| Metric | Value |
|---|---|
| Total vectors | {benign['total_vectors']} |
| Passed | {benign['passed']} |
| False blocks | {benign['false_blocks']} |
| False block rate | {benign['false_block_rate']:.1%} |

## Red-Team Gate

| Metric | Value |
|---|---|
| Passed tests | {redteam['passed_tests']} |
| Status | {redteam['status']} |

---
_This file is generated by `scripts/update_status_md.py`._
"""

    STATUS_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {STATUS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
